/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-dim": "#cbdbf5",
        "on-tertiary-container": "#8b909a",
        "on-secondary-fixed-variant": "#004395",
        "inverse-surface": "#213145",
        "secondary-container": "#2170e4",
        "surface-container-highest": "#d3e4fe",
        "on-secondary-fixed": "#001a42",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#00174a",
        "secondary-fixed-dim": "#adc6ff",
        "primary-fixed": "#dbe1ff",
        "surface-tint": "#435b9f",
        "on-surface-variant": "#444650",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "secondary": "#0058be",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c5c6d2",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#171c23",
        "on-tertiary-fixed-variant": "#424750",
        "outline": "#757682",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#2a4386",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#758dd5",
        "tertiary-fixed": "#dee2ed",
        "background": "#f8f9ff",
        "on-primary": "#ffffff",
        "surface": "#f8f9ff",
        "primary-fixed-dim": "#b3c5ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#b3c5ff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#c2c6d1",
        "primary-container": "#002366",
        "tertiary": "#10151c",
        "primary": "#00113a",
        "tertiary-container": "#242931",
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#fefcff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "lg": "48px",
        "md": "24px",
        "container-max": "1200px",
        "sm": "16px",
        "xs": "8px",
        "xl": "80px",
        "unit": "4px"
      },
      fontFamily: {
        "h2": ["Inter", "sans-serif"],
        "button": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "button": ["16px", { lineHeight: "1.0", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
